### ISSUE TITLE
cant get the examples to work

### ISSUE THREAD

**Issue by Lodugh** [don-tnowe/godot-wyvernbox-inventory#1]
Just cloned the whole repository to try out the examples but there is some kind of issue with the files. I can start the test 2D scene if I restart after importing but then it gives the error "Attempt to call function 'file_exists' in base 'null instance' on a null instance." in the load_state function in the ground_items_manager.gd.

**Comment by don-tnowe** [comment]
There's autosave used in the example, so it tries to find the save file. In Godot 4 file access API changed, so not all was translated correctly when porting.

Thanks for the report! Will fix soon.

**Comment by Lodugh** [comment]
Huh, now I get the same error in the inventory.gd.

**Comment by don-tnowe** [comment]
I just cleared the saves folder and actually, there's a different error.

I will investigate further and try fix all errors that happen
