### ISSUE TITLE
Examples: some text relies on translations for string interpolation

### ISSUE THREAD

**Issue by Basilicum** [don-tnowe/godot-wyvernbox-inventory#17]
Hi!
Getting into the Plugin blind is quite overwhelming and it'd really help to have a Demo Project to look into for reference.

Thanks for your time.

**Comment by don-tnowe** [comment]
There is one?

If you install the plugin without disabling the `example/` folder, you get a 2D and 3D scene with all main features and some hint popups.

**Comment by don-tnowe** [comment]
I'll need to fix that, yeah.

The translated string is supposed to have a `"%s"` to insert a number, but a new user won't have the translation files added. I'll probably make it a hard-coded string for the example.

**Comment by don-tnowe** [comment]
On toolbar, `Project > Project Settings > Localization -> Add` and add `example/translation/ui.en.translation`.

I'm quickly gonna update it so it's not gonna be needed.
