### ISSUE TITLE
Not so beginner friendly feeling.

### ISSUE THREAD

**Issue by makaempffer** [don-tnowe/godot-wyvernbox-inventory#20]
This is kind of an issue but more so an ask of help to not so smart(like me) users that need more guidance into using the plugin, probably a step by step setup of a grid inventory on a project something like that... I'm going to keep trying the plugin of course and if I get to understanding I'll make myself and upload it somewhere.

**Comment by don-tnowe** [comment]
Interesting. I'd love to, but I thought setup was currently easy - just 4 steps 🤔 So of course it's just me knowing too much.

For an outside perspective, what specifically confused you? I can improve the example, the setup section in `README` and the plugin's warning messages, but I'd need to know what specifically causes problems.

**Comment by makaempffer** [comment]
Sorry for the delay! Mainly the issue I had was not knowing if I had to append the gd scripts to the inventory scene or just make it as a child of another scene because the two exists, when the warning to use.
And yes it is pretty straight forward actually I ended up getting it to work after trying longer.

**Comment by makaempffer** [comment]
Now that I read the readme more carefully you already specified my issue there lol my bad.
