### ISSUE TITLE
How To Coloured Item Rarity Names?

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernbox-inventory#21]
How to added arbitrary item rarity / quality to the item names like with Flare / Diablo 1 & 2 / World of Warcraft / Path of Exile Terraria etc?

Examples:
https://github.com/flareteam/flare-game + https://flarerpg.org/ + https://youtu.be/OLrUYYulcss?t=42 + [Example Item Rarities](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/100ed1d2-acc6-4d92-a73e-fde0926cd90c/df6jypp-917d856f-d331-464c-8789-5dad27136f4f.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzEwMGVkMWQyLWFjYzYtNGQ5Mi1hNzNlLWZkZTA5MjZjZDkwY1wvZGY2anlwcC05MTdkODU2Zi1kMzMxLTQ2NGMtODc4OS01ZGFkMjcxMzZmNGYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.UHSu0wd-5Kc4WL-VrOEx_EvA3QVc9PXoSylSWFkEeAI) + 
https://www.deviantart.com/withinamnesia/art/Item-Quality-Table-918001789

Is there a simple tweak? I enjoy the name plate colour item rarity / quality. Yet I hope there is a feature for supporting arbitrary item rarity / quality to the item names; thank you for your time and keep up the good work. Also how can combat be tied to this system and is there an example or a combined 2D + 3D wyvern shield+inventory coming out hopefully? Something like this on github perhaps? https://www.youtube.com/watch?v=pBoXqW4RykE&list=PL3cGrGHvkwn0zoGLoGorwvGj6dHCjLaGd&index=1

**Comment by don-tnowe** [comment]
Yep, it's been a feature from the start. You're looking for `&"back_color"`, add it with a `Color`-type value to `extra_properties` in the inspector; or through code, `item_stack.extra_properties.back_color = Color(<red>, <green>, <blue>)`.

This dropdown when editing an `ItemType` shows more and lets you add quickly:

![image](https://github.com/don-tnowe/godot-wyvernbox-inventory/assets/67479453/f085ed7f-a168-4994-af69-fad5843990cd)

I plan on making an example game combining both addons, but I'd like to keep them isolated by design - not all games would need both.

**Comment by don-tnowe** [comment]
I'm not sure I'm catching what you're saying here.

- Colors can be changed, some items in the example (*folder downloaded with the addon*) already have a custom color, and my last comment mentions how to add it.
- Save/load already works, working in the example and the simplest way to enable it is through two properties in `InventoryView`.
- Items can already have arbitrary names - to add a suffix, do `item_stack.name_with_affixes.push_back(<suffix>)`, to add a prefix, do `item_stack.name_with_affixes.push_front(<prefix>)`, to change the base name, do `item_stack.name_with_affixes.replace(null, <name>)`. It's also done in the example's "Enchant" craft.

Could you please explain the proposed feature in more detail, perhaps with examples?

**Comment by WithinAmnesia** [comment]
Arbitrary name colours update example I picture something like a github version of what you already have that is expanded to have the changes you described so as to have the arbitrary item quality / rarity colour on the name letters and not just the name plate behind the letters. https://vanilla-twinhead.twinstar.cz/?item=647 To match this conventional item format found in most games like Diablo World of Warcraft and Path of Exile. Or how ever you word it to ask you to please try and make a version of this inventory godot addon that closely resembles what most people come to expect from these kinds of item colour quality / rarity system format. Please can you make a version that has the colour on the letters of the name? If you do it everyone can use it and you can probably do the best job of it too.

**Comment by don-tnowe** [comment]
Ah, that.

I could make it a setting, yeah. Right now customization of prefabs is kinda DIY, so you just edit the scene or script. It's not user-friendly yet, but I'd be happy to know a better way to implement customization in a better way.

This'd be related to #14 .

**Comment by don-tnowe** [comment]
Here ya go, added this as a property.

**Comment by WithinAmnesia** [comment]
Awwwwwwe thank you! That's really good. Super awesome ya!

**Comment by WithinAmnesia** [comment]
How do you like make the names on items use the colour text? Like is there any examples or like i tried monkeying around with adding under back_color like
"back_color_name_tint" 1,1,1,1, but matching the formats but I am not sure how to turn on the color text?
What is an example? It looks like it works its just what must done done to use it lol? Monkey brain time.

**Comment by WithinAmnesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernbox-inventory/assets/86871191/61c3df6c-136c-4065-b30e-1fcbf6296c8c)
I think this is it?
"## At [code]1.0[/code], the item's name will fully take the color from the [code]&"back_color"[/code] extra property."
So set the selected 0.1 value in the screenshot to 1.0 instead of 0.1 for it to work I suppose?

**Comment by WithinAmnesia** [comment]
![image](https://github.com/don-tnowe/godot-wyvernbox-inventory/assets/86871191/2d149d57-dd86-4b91-ac61-038fc1be3997)
It works great!
