### ISSUE TITLE
Example ARPG Project

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernbox-inventory#22]
![image](https://github.com/don-tnowe/godot-wyvernbox-inventory/assets/86871191/7fbe0722-4d9f-4604-858f-e08f9e5569a1)
https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/21#issuecomment-1759017822
"I plan on making an example game combining both addons..." @don-tnowe 
https://www.youtube.com/playlist?list=PL3cGrGHvkwn0zoGLoGorwvGj6dHCjLaGd
Example ARPG combat system but its not linked to your health / combat / trigger and effect combat system.

https://github.com/WithinAmnesia/ARPG/discussions/4#discussioncomment-7051445
I created a rough starter movement work last month out of all MIT and CC0 assets but paused to figure out big happy combat and inventory integration.

Are you interested in helping combine these three into one example project for Godot 4? You mentioned combining the inventory and combat systems into a project. Could you please adapt my little Godot 4 tiny ARPG example with the tiny little tileset and it has animations all ready to go? It just needs a little guidance to help put the inventory, stats and combat all together and work nice and happy for everyone to enjoy. As like a happy little 2D MIT ARPG in Godot 4 that is like a little starter kit for independent games like zelda or diablo or warcraft or Baldur's Gate or any nice classic rpg for the community forever free.

**Comment by don-tnowe** [comment]
Your ambition is admirable, but there doesn't seem to be enough in that project for me to consider using that over something of my own.

**Comment by WithinAmnesia** [comment]
Ya hey can we together to make something super cool for everyone hey? MIT and combat like zelda little melee attack health bars and status effects, little stats and happy inventory hey? Make a nice happy start kit for people to make cool ARPG games with? Maybe just a tiny little example? Like SNES zelda in scale but with your inventory and combat like a little rpg example template for godot 4? Hey watcha think about that? I can help too but you are way better at coding than me ya lol.
