### ISSUE TITLE
Wyvern Combat Features (Important Depth Features) [9 Key Points]

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernbox-inventory#24]
Wyvern Combat Features (Important Depth Features) [~'Clearer To-Do List']:
----------------
0.) Colour Text Item Quality / Rarity (Already Implemented; Good Job!)
1.) WASD Flare / Zelda Style ARPG Combat Template Example
2.) Experience / Level Scaling
3.) Arbitrary Attributes / Statistics / Damage Types and Elements
4.) Arbitrary Resource System
5.) Floating Point / Percentage % / Complex Number Support
6.) Abilities / Powers
7.) Skilltress / Powertrees
8.) Equipment Sets
9.) Step Sounds / Inventory Item Sounds
----------------
https://github.com/don-tnowe/godot-wyvernbox-inventory/issues/23#issuecomment-1765407365
"For future, I'd appreciate if separate topics were files as separate issues! It would make discussion less cluttered and give me a clearer to-do list!"
Please feel free to give awesome feedback and support!

**Comment by don-tnowe** [comment]
Tracked in [godot-wyvernquest-rpg/#1](https://github.com/don-tnowe/godot-wyvernquest-rpg/issues/1).
