### ISSUE TITLE
Need help with removing specific amounts of Items 

### ISSUE THREAD

**Issue by KometFox** [don-tnowe/godot-wyvernbox-inventory#28]
I have this code here for a crafting system where I am trying to get a dictionary of required items and a dictionary of items the player has and then doing some code statement that removes specific amount of items in players inventory, instead I have this issue where it removes the count of the items from all items stack instead of only removing by how much needs to be removed as in removing exactly only 10 amount of type "wheat" when the player has 2x100 stacks of "wheat" item, and the other issues is that the inventory doesn't get updated with the new item amounts unless I click on one of those items. 

```
func CheckForIngredients():
	var Ingredients: Dictionary = Recipes[SelectedRecipe]["Ingredients"]
	var Player = get_tree().get_nodes_in_group("Player")[0]
	var PlayerItems = Player.GUIMan.GetGUIName("PlayerGUI").GUI["Inventory"].inventory.items
	var PlayerInventory = Player.GUIMan.GetGUIName("PlayerGUI").GUI["Inventory"].inventory
		
	var MatchReq: bool = false #If the Player has enough items for the required crafting item
	
	for Items in PlayerItems:
		for IngItems in Ingredients.keys():
			var IngName = load(IngItems).name

			if Items.item_type.name == IngName:
				if Items.count >= Ingredients[IngItems]:
					Items.count -= Ingredients[IngItems]
```

**Comment by KometFox** [comment]
Because I want to implement my own crafting system which is different. The difference I have is that mine is planned to spawn the items at a specific spot instead of giving the items directly to the player and I have a terminal like interface for interacting with the crafting stations so in other words I was trying to implement a slightly more immersive way of crafting items since my ore refinery machine is made similar. 

Alright I will try the `consume_items` function and see if it does what I need, thanks for the reply.

**Comment by don-tnowe** [comment]
Hmm. That method is part of the `Inventory` class, so if they're placed in the world it can't be used... but I see you have an inventory, which hints that `ItemConversion`s should, in fact, be used like in the example? I'm confused about how your things are actually implemented.

Anyway, docs description for `consume_items`:

>Consumes items matching types and patterns inside `item_type_counts` (first param. note: keys are item types, values are counts)
>Returns all stacks consumed. 
>Set `check_only` (second param) to not actually consume items - this is useful to highlight stacks that would be affected, or show which items are not of sufficient amount. 
>**Note**: this method modifies the `item_type_counts` (first param) dictionary. The resulting values will match the types/patterns that could not be fully fulfilled. 

Docs can be accessed by pressing F1 and searching the class, if the plugin was enabled in Project Settings.

**Comment by KometFox** [comment]
Ah so it just needs a dictionary of loaded resource types of type ItemStacks and it's value the amount it should consume, now i get it. The description for consume_items was not clear enough to be honest so I didn't understand at first what kind of dictionary it exactly needs for this function to work. I changed my code now and it is working as I wanted it to do in the first place, thanks. 
```
	var Ingredients: Dictionary = Recipes[SelectedRecipe]["Ingredients"]
	var Player = get_tree().get_nodes_in_group("Player")[0]
	var PlayerItems = Player.GUIMan.GetGUIName("PlayerGUI").GUI["Inventory"].inventory.items
	var PlayerInventory = Player.GUIMan.GetGUIName("PlayerGUI").GUI["Inventory"].inventory
		
	var MatchReq: bool = false #If the Player has enough items for the required crafting item
	
	var NeoDict = {}
	
	for Items in Ingredients.keys():
		NeoDict[load(Items)]= Ingredients[Items] 
	
	PlayerInventory.consume_items(NeoDict)
```
