### ISSUE TITLE
How does one use the 'Wvyern' series assets with Godot 4? How to make an ARPG like Diablo in Godot 4?

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernbox-inventory#3]
I'm not sure where to ask this so I came here to ask @don-tnowe what I should do to start building a Diablo / Zelda engine / blue print / template in Godot?

I come from various game engines including Flare https://github.com/flareteam and unreal and I am trying to figure out how to use the Lucifer CC0 assets to create a Diablo 'game engine' in Godot 4 https://itch.io/c/1557879/lucifer . I have a giant RPG series I have been trying to make on various game engines and now I am on Godot 4 to create a version of it that is 2D. I need to assemble the ~engine that is like Diablo that runs on Godot 4. What should I do? Where should I start? I am watching tutorial series:
https://www.youtube.com/watch?v=pBoXqW4RykE&list=PL3cGrGHvkwn0zoGLoGorwvGj6dHCjLaGd&ab_channel=DevWorm
https://www.youtube.com/watch?v=bS-tX2HopW0&ab_channel=GDQuest
https://www.youtube.com/watch?v=oq_s5Ivg4Ow&ab_channel=GameDevelopmentCenter
https://www.youtube.com/watch?v=0mUoRdYe0s4&list=PLMQtM2GgbPEVuTgD4Ln17ombTg6EahSLr&ab_channel=MakerTech
https://www.youtube.com/watch?v=AkKywZDJNeE&ab_channel=Arkeve
https://www.youtube.com/watch?v=Vi0V1D5A7qI&ab_channel=FoozleCC
https://www.youtube.com/playlist?list=PL9FzW-m48fn2SlrW0KoLT4n5egNdX-W9a

There is no ~complete Diablo style engine 'template' for Godot 4 and I'm trying to port over my RPG work from various game engines into a 2D game version on Godot 4 from engines and games. Such as like with Baldur's Gate, World of Warcraft, Flare, Unity, RPG Maker, Unreal and a lot of books of concepts and game design systems but it mostly runs on a game engines like Diablo / Zelda / ~'Grand RPGs' like WoW and or Baldur's Gate. What should one do to get a ~Diablo / Zelda / ~'Grand RPG' style engine on Godot 4? I figured you might be a very talented person to ask to start.

**Comment by don-tnowe** [comment]
Hello! Thanks for showing interest in Wyvernbox and Wyvernshield (*these two don't get a lot of that tbh*)

While Wyvernbox is basically a full-blown GUI inventory with a scripting interface and you won't need to do much, Wyvernshield (*for Godot 4 specifically*) only handles stats, triggered effects and status effects. It doesn't cover how actual combat works, with combat moves and collisions, or movement, or dialogues or other RPG-specific things. You'll need to know how to make action combat in base Godot 4 without addons - and use Wyvernshield as something between the "this thing must happen" and "this is how the results are applied".

But you can see how combat can be done in Wyvernshield's Example project (*basically just clone https://github.com/don-tnowe/godot-wyvernshield-triggers*) and adapt to how you see fit.

I can't really say much to this very general request, but I'm open to questions on how the addons work or how to implement specific mechanics!

**Comment by WithinAmnesia** [comment]
I should think of better reply. Thank you though and I am glad you are so helpful. You are right there are a lot of unknowns still to solve, bit by bit though.

**Comment by WithinAmnesia** [comment]
> Hello! Thanks for showing interest in Wyvernbox and Wyvernshield (_these two don't get a lot of that tbh_)
> 
> While Wyvernbox is basically a full-blown GUI inventory with a scripting interface and you won't need to do much, Wyvernshield (_for Godot 4 specifically_) only handles stats, triggered effects and status effects. It doesn't cover how actual combat works, with combat moves and collisions, or movement, or dialogues or other RPG-specific things. You'll need to know how to make action combat in base Godot 4 without addons - and use Wyvernshield as something between the "this thing must happen" and "this is how the results are applied".
> 
> But you can see how combat can be done in Wyvernshield's Example project (_basically just clone https://github.com/don-tnowe/godot-wyvernshield-triggers_) and adapt to how you see fit.
> 
> I can't really say much to this very general request, but I'm open to questions on how the addons work or how to implement specific mechanics!

Imagine if we combine of these examples to work on Godot 4+ as CC0 / MIT / ~'Public Domain' for combat mechanics:
https://github.com/flareteam/flare-game/releases/tag/v1.14
https://redbladegames.netlify.app/randomlooter/index.html
https://itch.io/c/1557879/lucifer
https://foozlecc.itch.io/lucifer-exterior-tileset
https://foozlecc.itch.io/lucifer-warrior
https://www.youtube.com/watch?v=AkKywZDJNeE&ab_channel=Arkeve
https://www.youtube.com/playlist?list=PL3cGrGHvkwn0zoGLoGorwvGj6dHCjLaGd
https://www.solarus-games.org/games/the-legend-of-zelda-book-of-mudora/
Please ask questions and share ideas.

**Comment by WithinAmnesia** [comment]
I created an open source GitHub repository for making an Open Source MIT license Action Role Playing Game template for Godot Engine 4+. https://github.com/WithinAmnesia/ARPG . It's a start. I think if its made open and community driven it can empower m any people across the world. Yet it still early days and humble beginnings.
