### ISSUE TITLE
JDungeon Wyvern Support

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernbox-inventory#32]
https://github.com/jonathaneeckhout/jdungeon
JDungeon is a Godot 4.NET MMORPG and could be made even better with your super great plugins and RPG features. Currently the JDungeon Godot community could use some help with some simple features but the MMORPG core is super excellent: https://github.com/jonathaneeckhout/jdungeon/issues/238 Please give feedback. What do you think hey?

**Comment by don-tnowe** [comment]
They are free to use this per the project's license. I don't think I need to do much to support this project specifically - in fact, it's best if an addon works in any project with minimal effort.

They might not even need my system - they already seem to have an inventory implemented.

**Comment by WithinAmnesia** [comment]
Okay that is good to hear. So the projects a quite similar, I wonder if the networking will add extra layers to think about to use your ideas on say the item rarity or crafting or any of the features found with your good work that could be beneficial to the JDungeon core starting features? Do you have any first thoughts or curiosities about the networking of it being online that should be considered with using your work added to the MMORPG features? What are your thoughts on Wyvern and JDungeon compatibility is there anything you'd like to see or are interested in with this kind of combination?
