### ISSUE TITLE
Is it possible to use it with a container?

### ISSUE THREAD

**Issue by Abab-bk** [don-tnowe/godot-wyvernbox-inventory#33]
Using it with a container now causes dislocations. I wonder if it's possible to use it with a container.🙂

**Comment by don-tnowe** [comment]
Yes - should support containers or even rotation/scale. If it's breaking, I'd like a Minimal Reproduction Project so I can find the issue!

**Comment by don-tnowe** [comment]
Actually, I remember a specific arrangement of nodes make items move independent of background and scale, but I'd still like an MRP to see the specific arrangement to code a guard case against.

**Comment by Abab-bk** [comment]
[TestProject.zip](https://github.com/don-tnowe/godot-wyvernbox-inventory/files/14469377/TestProject.zip)
Here. plz check control.tscn and control_2.tscn.

**Comment by don-tnowe** [comment]
Should now be fixed. Thanks!

Also, inventories only need one Grabber+Tooltip in the entire game scene, not per inventory! I will also try to make the warning not show up when one is present, I'm assuming it just kept nagging you in every scene so I'll try prevent misunderstandings. I'm also open to discussion on the best way to do it.
