### ISSUE TITLE
Godot Wyvernbox Inventory + Godot-Voxel / Blockygame Demonstration Integration.

### ISSUE THREAD

**Issue by WithinAmnesia** [don-tnowe/godot-wyvernbox-inventory#34]
I've been working on making a big scale game and I have found an infinite chunk system that works with multiplayer. But it's 3D and I have yet to find an inventory system that is equal better or even close to what your inventory system offers. And I was thinking of working with this inventory system and I'll eventually get my inventory working. But it has a limit where there are chests there are item slots there are basic drop and pick up features like in Minecraft and it has a limit.

This inventory system is deeper it has crafting it has Diablo Style Inventory management and it has Rarities of items it has a lot more depth to it and I'm thinking of getting a community demonstration working as an inventory but I want to go beyond that and I'm thinking to ask you not to do all the work but to give your advice as this progresses. I'd rather do it early ask you cuz you seem to have the Deep talent and skill sets to know what should be done and this is for the community this inventory thing and so was my project. So I want to open up communication and talk I've been getting better and better at coding doing the work myself. I'm at the point where I am polishing up my inventory demonstration example it has the blockygame demo and the DevLogLogan video tutorial systems working together.

It's mostly done it just needs some extra features and it'll actually get there but it has a limit to its growth and I want to talk now as I work on this and get the ball rolling on that and see how you feel about this how you think about this stuff and go from there. As because I have a base for a multiplayer ARPG and it has infinite chunk systems it's just the RPG systems like the inventory I'd imagine chests stats attributes items are Rarity the systems of depth and progression experience these things Mana Health. These type of things they need proper work and proper plans and stuff that; so I figured just talk to you about it and get consultation for it cuz you seem to be one of the very few Experts of this for Godot.

Project Links:
https://github.com/WithinAmnesia/ARPG/tree/ARPG-Infinite-Worlds
https://www.youtube.com/watch?v=V79YabQZC1s
https://github.com/Zylann/voxelgame + https://github.com/Zylann/godot_voxel
https://github.com/WithinAmnesia/ARPG/discussions/16

**Comment by don-tnowe** [comment]
Friend, Github is for bug reports and feature requests - this one specifically is for my inventory system. I'd appreciate if it was kept just for that.

If you want to message me directly, you can just use Telegram or Discord, my username is the same.

I'm not seeing any question I can answer, but I'm open to answer questions on there.

**Comment by WithinAmnesia** [comment]
I am matthewroulston on discord my picture looks the same. I sent a friend request to don-tnowe#0798 . I had to look around for it but I found it eventually lol.
