### ISSUE TITLE
GroundItemManager from_array does not prevent duplicate items

### ISSUE THREAD

**Issue by Mazianni** [don-tnowe/godot-wyvernbox-inventory#4]
Hello!

When using the GroundItemManager class's to_array/from_array, from_array does not prevent duplicate items (or clear it's existing items). 

I noticed that inventories *do* prevent duplicates, so I didn't encounter an issue in my use-case (multiplayer serialization) until I implemented a ground item manager.

**Comment by don-tnowe** [comment]
Interesting. Seems I've overlooked that

Should be as easy as `for x in get_children(): x.free()`, as ground items are simply the manager's children.
