### ISSUE TITLE
[discussion] General weariness with plugin

### ISSUE THREAD

**Issue by Mazianni** [don-tnowe/godot-wyvernbox-inventory#8]
I'm starting to get fairly frustrated with the lack of documentation about how Wyvernbox works internally.

I've spent the past three days chasing down undocumented behavior, with more time spent on that, getting what *should* be a fairly easy-to-stand-up system to work like I expect it to.

As it stands, I keep running into issues and I have NO clue what I'm doing wrong, and I can't chase down everything because I don't know this code very well.

**Comment by Mazianni** [comment]
alright i'm going to close this because i think i actually found an issue in Godot and not the plugin.

**Comment by don-tnowe** [comment]
So what was the problem? Could still be my issue, and if it's not I could at least make a workaround or comment so it's not as confusing.
