### ISSUE TITLE
[documentation] / [bug] GrabbedItemStackView does not grab unless visible is set to false in scenetree.

### ISSUE THREAD

**Issue by Mazianni** [don-tnowe/godot-wyvernbox-inventory#9]
Either change this behavior or document it, please.

I spent four hours trying to understand what I was doing wrong.

**Comment by don-tnowe** [comment]
THANK YOU so much for pointing this out. There are a few things that just grew on me after using this for so long, and you need to ensure every time.

I see a solution already but will try reproduce to make sure.
